default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: arqsoft
  password: 123
  host: list_pay_db
  socket: /tmp/mysql.sock
development:
  <<: *default
  database: lists
